export default {
  results: [
    {
      adult: false,
      backdrop_path: "/83oeqwN64WtafGoITvsOzjKIQaM.jpg",
      id: 718930,
      title: "Bullet Train",
      original_language: "en",
      original_title: "Bullet Train",
      overview:
        "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
      poster_path: "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
      media_type: "movie",
      genre_ids: [28, 35, 53],
      popularity: 2985.795,
      release_date: "2022-07-03",
      video: false,
      vote_average: 7.501,
      vote_count: 1700,
    },
    {
      adult: false,
      backdrop_path: "/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg",
      id: 84773,
      name: "The Lord of the Rings: The Rings of Power",
      original_language: "en",
      original_name: "The Lord of the Rings: The Rings of Power",
      overview:
        "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
      poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 18],
      popularity: 4211.295,
      first_air_date: "2022-09-01",
      vote_average: 7.689,
      vote_count: 1046,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/pfAZP7JvTTxqgq7n6A1OYgkAdEW.jpg",
      id: 894205,
      title: "Werewolf by Night",
      original_language: "en",
      original_title: "Werewolf by Night",
      overview:
        "On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple following the death of their leader. In a strange and macabre memorial to the leader’s life, the attendees are thrust into a mysterious and deadly competition for a powerful relic—a hunt that will ultimately bring them face to face with a dangerous monster.",
      poster_path: "/1n2q0Y1pX8PkQh9imqGbNH7Bw4q.jpg",
      media_type: "movie",
      genre_ids: [28, 14, 27],
      popularity: 714.998,
      release_date: "2022-09-25",
      video: false,
      vote_average: 7.4,
      vote_count: 352,
    },
    {
      adult: false,
      backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
      id: 94997,
      name: "House of the Dragon",
      original_language: "en",
      original_name: "House of the Dragon",
      overview:
        "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
      poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
      media_type: "tv",
      genre_ids: [10765, 18, 10759],
      popularity: 4456.372,
      first_air_date: "2022-08-21",
      vote_average: 8.5,
      vote_count: 1736,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/bwEtMHwa2N4LMIiRS6TfFrnjhQb.jpg",
      id: 92783,
      name: "She-Hulk: Attorney at Law",
      original_language: "en",
      original_name: "She-Hulk: Attorney at Law",
      overview:
        "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
      poster_path: "/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg",
      media_type: "tv",
      genre_ids: [35, 10765],
      popularity: 5257.326,
      first_air_date: "2022-08-18",
      vote_average: 6.899,
      vote_count: 1009,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
      id: 83867,
      name: "Star Wars: Andor",
      original_language: "en",
      original_name: "Star Wars: Andor",
      overview:
        "The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
      poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 10768],
      popularity: 1024.151,
      first_air_date: "2022-09-21",
      vote_average: 7.906,
      vote_count: 133,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/iS9U3VHpPEjTWnwmW56CrBlpgLj.jpg",
      id: 642885,
      title: "Hocus Pocus 2",
      original_language: "en",
      original_title: "Hocus Pocus 2",
      overview:
        "It’s been 29 years since someone lit the Black Flame Candle and resurrected the 17th-century sisters, and they are looking for revenge. Now it is up to three high-school students to stop the ravenous witches from wreaking a new kind of havoc on Salem before dawn on All Hallow’s Eve.",
      poster_path: "/7ze7YNmUaX81ufctGqt0AgHxRtL.jpg",
      media_type: "movie",
      genre_ids: [14, 35, 10751],
      popularity: 3140.461,
      release_date: "2022-09-27",
      video: false,
      vote_average: 7.7,
      vote_count: 683,
    },
    {
      adult: false,
      backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
      id: 616037,
      title: "Thor: Love and Thunder",
      original_language: "en",
      original_title: "Thor: Love and Thunder",
      overview:
        "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
      poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
      media_type: "movie",
      genre_ids: [14, 28, 35],
      popularity: 1431.028,
      release_date: "2022-07-06",
      video: false,
      vote_average: 6.743,
      vote_count: 4169,
    },
    {
      adult: false,
      backdrop_path: "/qtfMr08KQsWXnCHY0a96N8NpQ2l.jpg",
      id: 30984,
      name: "Bleach",
      original_language: "ja",
      original_name: "ブリーチ",
      overview:
        "For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.",
      poster_path: "/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
      media_type: "tv",
      genre_ids: [10759, 16, 10765],
      popularity: 374.34,
      first_air_date: "2004-10-05",
      vote_average: 8.344,
      vote_count: 1273,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/3r3tZgKTw1554hcFoUfydLHE38w.jpg",
      id: 338947,
      title: "Hellraiser",
      original_language: "en",
      original_title: "Hellraiser",
      overview:
        "A young woman struggling with addiction comes into possession of an ancient puzzle box, unaware that its purpose is to summon the Cenobites, a group of sadistic supernatural beings from another dimension.",
      poster_path: "/f9ZAIUxTTk23vo1BC9Ur1Rx5c2E.jpg",
      media_type: "movie",
      genre_ids: [27, 9648],
      popularity: 192.675,
      release_date: "2022-09-28",
      video: false,
      vote_average: 6.6,
      vote_count: 176,
    },
    {
      adult: false,
      backdrop_path: "/1UlTowc5vfrgXUVT6OnlU0TOiij.jpg",
      id: 616820,
      title: "Halloween Ends",
      original_language: "en",
      original_title: "Halloween Ends",
      overview:
        "Four years after the events of Halloween in 2018, Laurie has decided to liberate herself from fear and rage and embrace life. But when a young man is accused of killing a boy he was babysitting, it ignites a cascade of violence and terror that will force Laurie to finally confront the evil she can’t control, once and for all.",
      poster_path: "/3aEJDJ9O8lsRMM9Xaxxm5kNyt0N.jpg",
      media_type: "movie",
      genre_ids: [27, 53],
      popularity: 722.729,
      release_date: "2022-10-12",
      video: false,
      vote_average: 7.33,
      vote_count: 50,
    },
    {
      adult: false,
      backdrop_path: "/iHc14vucwUMl6WuvQa4iPfoEdy9.jpg",
      id: 799546,
      title: "Luckiest Girl Alive",
      original_language: "en",
      original_title: "Luckiest Girl Alive",
      overview:
        "A successful woman in New York City finds her life upended when she is forced to confront a dark truth that threatens to unravel her meticulously crafted life.",
      poster_path: "/e0vrbTmTf2ZcW5CIS9qJ8FDbsU9.jpg",
      media_type: "movie",
      genre_ids: [18, 53, 9648],
      popularity: 235.557,
      release_date: "2022-09-30",
      video: false,
      vote_average: 6.693,
      vote_count: 179,
    },
    {
      adult: false,
      backdrop_path: "/o5Uy3zM1SNxzoMwy5H04GQAmfNF.jpg",
      id: 301502,
      title: "Blonde",
      original_language: "en",
      original_title: "Blonde",
      overview:
        "From her volatile childhood as Norma Jeane, through her rise to stardom and romantic entanglements, this reimagined fictional portrait of Hollywood legend Marilyn Monroe blurs the lines of fact and fiction to explore the widening split between her public and private selves.",
      poster_path: "/jOgbnL5FB30pprEjZaY1E1iPtPM.jpg",
      media_type: "movie",
      genre_ids: [18],
      popularity: 467.563,
      release_date: "2022-09-16",
      video: false,
      vote_average: 6.519,
      vote_count: 533,
    },
    {
      adult: false,
      backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
      id: 361743,
      title: "Top Gun: Maverick",
      original_language: "en",
      original_title: "Top Gun: Maverick",
      overview:
        "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
      poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
      media_type: "movie",
      genre_ids: [28, 18],
      popularity: 1063.638,
      release_date: "2022-05-24",
      video: false,
      vote_average: 8.359,
      vote_count: 4261,
    },
    {
      adult: false,
      backdrop_path: "/5vUux2vNUTqwCzb7tVcH18XnsF.jpg",
      id: 113988,
      name: "Dahmer – Monster: The Jeffrey Dahmer Story",
      original_language: "en",
      original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
      overview:
        "Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?",
      poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
      media_type: "tv",
      genre_ids: [18, 80],
      popularity: 6689.831,
      first_air_date: "2022-09-21",
      vote_average: 8.292,
      vote_count: 864,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/5DUMPBSnHOZsbBv81GFXZXvDpo6.jpg",
      id: 114410,
      name: "Chainsaw Man",
      original_language: "ja",
      original_name: "チェンソーマン",
      overview:
        "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.",
      poster_path: "/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
      media_type: "tv",
      genre_ids: [16, 10759, 10765, 35],
      popularity: 288.128,
      first_air_date: "2022-10-12",
      vote_average: 8.1,
      vote_count: 20,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/zgMjGYxVKwUKvl5UdT9jNkiNyCe.jpg",
      id: 1024530,
      title: "Grimcutty",
      original_language: "en",
      original_title: "Grimcutty",
      overview:
        "A suburban teen girl and her little brother must stop a terrifying internet meme brought to life by the hysteria of their parents.",
      poster_path: "/qvg75YJMfbHeDNirUrrgBMQImRn.jpg",
      media_type: "movie",
      genre_ids: [27],
      popularity: 152.979,
      release_date: "2022-10-10",
      video: false,
      vote_average: 6.299,
      vote_count: 72,
    },
    {
      adult: false,
      backdrop_path: "/z8KsgBFtduX5bS1yVkjoGo4L7KJ.jpg",
      id: 597922,
      title: "The Greatest Beer Run Ever",
      original_language: "en",
      original_title: "The Greatest Beer Run Ever",
      overview:
        "Chickie wants to support his friends fighting in Vietnam, so he does something wild—personally bring them American beer. What starts as a well-meaning journey quickly changes Chickie’s life and perspective. Based on a true story.",
      poster_path: "/e1kgnjLRIWRRz772hAOTz57YKR6.jpg",
      media_type: "movie",
      genre_ids: [18, 35, 10752],
      popularity: 978.745,
      release_date: "2022-09-30",
      video: false,
      vote_average: 7.807,
      vote_count: 210,
    },
    {
      adult: false,
      backdrop_path: "/rjnnQOSntiuiHIbYKy4oessqaKA.jpg",
      id: 126254,
      name: "The Midnight Club",
      original_language: "en",
      original_name: "The Midnight Club",
      overview:
        "At a manor with a mysterious history, the 8 members of the Midnight Club meet each night at midnight to tell sinister stories – and to look for signs of the supernatural from the beyond.",
      poster_path: "/2Y4F9BHkacKIMnDBZI3GGKpG1If.jpg",
      media_type: "tv",
      genre_ids: [18, 9648],
      popularity: 470.151,
      first_air_date: "2022-10-07",
      vote_average: 7.5,
      vote_count: 39,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/iiaU8m4kUyDnbqtlr2hyiXYUlcH.jpg",
      id: 723419,
      title: "Mr. Harrigan's Phone",
      original_language: "en",
      original_title: "Mr. Harrigan's Phone",
      overview:
        "Craig, a young boy living in a small town befriends an older, reclusive billionaire, Mr. Harrigan. The two form a bond over books and an iPhone, but when the man passes away the boy discovers that not everything dead is gone.",
      poster_path: "/gPn9e8eP7TeKQU4IeWAMzOajR40.jpg",
      media_type: "movie",
      genre_ids: [53, 18, 27],
      popularity: 1195.241,
      release_date: "2022-10-05",
      video: false,
      vote_average: 6.637,
      vote_count: 244,
    },
  ],
};